### ISSUE TITLE
关于上下文的一个问题

### ISSUE THREAD

**Issue by wxynf4** [JinghuiS/vdi#1]
作者你好，useOverlay弹出子窗口的vue上下文已经改变了。
我在子窗体里面使用了el-button，样式没了，包括useStore也是空的。
可以把父窗体的上下文注入进去吗

**Comment by JinghuiS** [comment]
@wxynf4 因为useOverlay是另外一个vue实例了，如果使用全局注册的组件应该是拿不到的，在子窗中直接使用从组件库中引用使用吧

**Comment by JinghuiS** [comment]
@wxynf4  我重新写了一个使用弹窗的库，https://github.com/JinghuiS/vue-modal-provider 用这个吧

**Comment by wxynf4** [comment]
> @wxynf4 因为useOverlay是另外一个vue实例了，如果使用全局注册的组件应该是拿不到的，在子窗中直接使用从组件库中引用使用吧

是的，另外一个vue实例就拿不到了，我参考了el plus的message组件，他里面用的render实现的，然后绑定了vnode的上下文，这样就不会丢失上下文了

**Comment by wxynf4** [comment]
> @wxynf4 我重新写了一个使用弹窗的库，https://github.com/JinghuiS/vue-modal-provider 用这个吧

赞赞赞

**Comment by JinghuiS** [comment]
@wxynf4 可以试试看，这个可以拿到实例，有什么问题再提issues吧
